version: '3.1'

services:
  ghost:
    image: ghost:4-alpine
    ports:
      - 8080:2368
    environment:
      database__client: mysql
      database__connection__host: db
      database__connection__user: root
      database__connection__password: example
      database__connection__database: ghost
    volumes:
      - "ghost:/var/lib/ghost"
    networks:
      - public
      - private
    depends_on:
      - db

  db:
    image: mysql:8.0
    restart: always
    environment:
      MYSQL_ROOT_PASSWORD: example
    volumes:
      - "db:/var/lib/mysql"
    networks:
      - private

volumes:
  db:
  ghost:

networks:
  public:
  private:
